### ISSUE TITLE
Working on local but not working as AWS

### ISSUE THREAD

**Issue by SuatcanYasan** [hajareshyam/pdf-creator-node#114]
"Error: html-pdf: Unknown Error\n/var/app/current/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs: error while loading shared libraries: libfontconfig.so.1: cannot open shared object file: No such file or directory\n"

I am trying to upload my PDF file to an AWS server. After completing the upload process, I provide the user with a URL. However, this system works locally, but it encounters issues on AWS.

**Comment by junaidranjha** [comment]
@SuatcanYasan did you find any solution?

**Comment by gregg-cbs** [comment]
That does not look like an error because of this package. That looks like you need to learn how to serve files from your aws server. You can raise this or stackoverflow or other forums and I am sure you will find answers there.

As a test you can put any working PDF file on your server and see if you are able to serve it.

**Comment by SuatcanYasan** [comment]
i didnt found any solution
