### ISSUE TITLE
CSS ressouces not loaded

### ISSUE THREAD

**Issue by BoxSo** [hajareshyam/pdf-creator-node#5]
I'm trying to define a html template which uses CSS for formatting. This seems not to work. If i view the template html file in browser, everything seems fine and formatting is ok.

the generated pdf does not respect the css, it seems the css is ignored.

The css file is loaded in html with the following statement:

`<head>
        <mate charest="utf-8" />
        <title>Datasheet</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    </head>`

**Comment by hajare-shyam** [comment]
Hi BoxSo, 
As per my understanding your are using Bootstrap CDN css. Please don't use CDN here

**Comment by hajareshyam** [comment]
Hi BoxSo,
This is not an issue. you are using CDN here. I will suggest you don't use CDN CSS for pdf generation.

**Comment by BoxSo** [comment]
Hey, you say only local stored and loaded css files are rendered?

**Comment by hajareshyam** [comment]
Yes, its only work on locally stored CSS file.

*Thanks & Regards *
*Shyam Hajare*

**Comment by abhikhedekar4241** [comment]
@hajare-shyam I tried using bootstrap locally. But still styles are not working. I am trying to use bootstrap grid structure.

**Comment by Kncarrier** [comment]
I also have ran into this issue. I am trying to use local bulma, and I think the issue is with the responsive nature of these frameworks. Things like text color and sizing are working fine, but when trying to use the responsive layout features of the framework, pdf-creator-node does not reflect those styles.

I assume this is because of the way frameworks like bulma and bootstrap use the window sizes and other properties of the browser to layout the page and this tool does not fully render the page during generation.

**Comment by abhikhedekar4241** [comment]
I ran out of options to make this work. So, I used "node-latex" to create pdf using latex. If you are stuck, you should try that.
